# Generated by Django 3.2.25 on 2026-05-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=255)),
                ('designer_email', models.CharField(max_length=255)),
                ('designer_contact', models.CharField(max_length=255)),
                ('designer_password', models.CharField(max_length=255)),
                ('designer_confirm_password', models.CharField(max_length=255)),
                ('designer_photo', models.FileField(upload_to='designer_image/')),
                ('bio', models.TextField()),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=255)),
                ('designer_email', models.CharField(max_length=255)),
                ('designer_contact', models.CharField(max_length=255)),
                ('design_title', models.CharField(max_length=255)),
                ('design_description', models.TextField()),
                ('category', models.CharField(choices=[('Lehenga', 'Lehenga'), ('Saree', 'Saree'), ('Chaniya', 'Chaniya'), ('Sherwani', 'Sherwani'), ('Kurta', 'Kurta'), ('Tuxedo', 'Tuxedo'), ('Boys', 'Boys Wear'), ('Girls', 'Girls Wear'), ('Men Accessories', 'Men Accessories'), ('Women Accessories', 'Women Accessories'), ('Men Footwear', 'Men Footwear'), ('Women Footwear', 'Women Footwear')], max_length=50)),
                ('design_image1', models.FileField(upload_to='designs_image1/')),
                ('design_image2', models.FileField(upload_to='designs_image2/')),
                ('design_image3', models.FileField(upload_to='designs_image3/')),
                ('charges', models.FloatField()),
                ('remarks', models.TextField()),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='rent_cloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=255)),
                ('designer_email', models.CharField(max_length=255)),
                ('designer_contact', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_contact', models.CharField(max_length=255)),
                ('rental_from', models.CharField(max_length=255)),
                ('rental_date', models.CharField(max_length=255)),
                ('charges', models.CharField(max_length=255)),
                ('total_charges', models.FloatField()),
                ('design_id', models.CharField(max_length=255)),
                ('image_design1', models.FileField(upload_to='rent_designs/')),
                ('image_design2', models.FileField(upload_to='rent_designs/')),
                ('image_design3', models.FileField(upload_to='rent_designs/')),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('return_status', models.CharField(default='Not Returned', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_contact', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_confirm_password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='rental_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('FINAL', 'Final')], max_length=20)),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to='payment_transactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnic.rent_cloths')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethnic.designs')),
            ],
            options={
                'unique_together': {('user_email', 'design')},
            },
        ),
    ]
