# Generated by Django 3.2.25 on 2026-05-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethnic', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
    ]
