# Generated by Django 3.2.25 on 2026-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethnic', '0004_remove_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
