# Generated by Django 3.2.25 on 2026-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethnic', '0005_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
